spring.application.name=api-produtos
spring.datasource.url=jdbc:mysql://localhost:3306/api_produtos
spring.datasource.username=boot
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true